// Code generated by scripts/embed-msb-runtime.sh; DO NOT EDIT.
// Checksums verified against upstream checksums.sha256 (v0.7.6).
package msbembed

func init() {
	assetChecksums["msb-linux-x86_64"] = "e5baba0cbc6628a39e12e297729dfa1b137f3e7ce13a3fa9cf5fd22e198cab9c"
	assetChecksums["libkrunfw-linux-x86_64.so"] = "ce9a749e8471e89aa5e2ad88de0c1581c3384c100bcb107a75bb12739a12d590"
}
