version: "2"
run:
  modules-download-mode: readonly
  tests: true
linters:
  enable:
    - copyloopvar
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    errcheck:
      check-blank: true
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - unparam
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
