package bridge

import (
	"fmt"
	"strings"
)

// InjectHostServices adds host service configuration to docker-compose override.
func InjectHostServices(baseCompose []byte, cfg *HostServiceConfig, hostIP string) ([]byte, error) {
	if !cfg.Enabled || hostIP == "" {
		return baseCompose, nil
	}

	// Build the override YAML
	override := buildOverrideYAML(hostIP)

	// Append to base compose
	result := string(baseCompose)
	result += "\n\n"
	result += "# Host Service Bridge - Auto-generated\n"
	result += "# Generated by: construct-cli host bridge\n"
	result += override

	return []byte(result), nil
}

// buildOverrideYAML builds the docker-compose override YAML for host services.
func buildOverrideYAML(hostIP string) string {
	var builder strings.Builder

	builder.WriteString("services:\n")
	builder.WriteString("  construct-box:\n")
	builder.WriteString("    extra_hosts:\n")
	fmt.Fprintf(&builder, "      - \"%s:host-gateway\"\n", hostIP)

	return builder.String()
}

// InjectEnvVars injects host service environment variables into container env.
func InjectEnvVars(env []string, cfg *HostServiceConfig, hostIP string) []string {
	if !cfg.Enabled || hostIP == "" {
		return env
	}

	// Get service environment variables
	serviceEnv := cfg.GetServiceEnv(hostIP)

	// Add to existing environment
	for key, value := range serviceEnv {
		env = append(env, fmt.Sprintf("%s=%s", key, value))
	}

	return env
}

// GetExtraHostsLine returns the extra_hosts line for docker-compose.
func GetExtraHostsLine(hostIP string) string {
	if hostIP == "" {
		return ""
	}
	return fmt.Sprintf("      - \"host.docker.internal:%s\"", hostIP)
}

// ValidateHostServicesConfig validates the host services configuration.
func ValidateHostServicesConfig(cfg *HostServiceConfig) error {
	if !cfg.Enabled {
		return nil
	}

	return cfg.Validate()
}

// ShouldEnableHostBridge checks if host bridge should be enabled.
func ShouldEnableHostBridge(cfg *HostServiceConfig) bool {
	if !cfg.Enabled {
		return false
	}

	// Check if any services are configured
	return len(cfg.Services) > 0
}

// GetManualHostIP returns the manual host IP if configured, otherwise empty string.
func GetManualHostIP(cfg *HostServiceConfig) string {
	return strings.TrimSpace(cfg.ManualHostIP)
}
