#!/usr/bin/env bash
# Fetch the upstream microsandbox release pair (msb + libkrunfw) pinned to
# the go.mod SDK version, verify both assets against the release's
# checksums.sha256, place them into internal/msbembed/assets/, and generate
# internal/msbembed/manifest_checksums.go. A build with -tags msbembed then
# embeds the pair (see internal/msbembed).
#
# Target platform: GOOS/GOARCH env, defaulting to the host. darwin/amd64 has
# no upstream assets and keeps the host-msb launch gate.
set -euo pipefail

GOOS_ARG="${GOOS:-$(go env GOOS)}"
GOARCH_ARG="${GOARCH:-$(go env GOARCH)}"

sdk_module="github.com/superradcompany/microsandbox/sdk/go"
sdk_version="$(go list -m "${sdk_module}" | awk '{print $NF}')"
case "${sdk_version}" in
v*) ;;
*) sdk_version="v${sdk_version}" ;;
esac

case "${GOOS_ARG}/${GOARCH_ARG}" in
linux/amd64)
	msb_asset="msb-linux-x86_64"
	lib_asset="libkrunfw-linux-x86_64.so"
	;;
linux/arm64)
	msb_asset="msb-linux-aarch64"
	lib_asset="libkrunfw-linux-aarch64.so"
	;;
darwin/arm64)
	msb_asset="msb-darwin-aarch64"
	lib_asset="libkrunfw-darwin-aarch64.dylib"
	;;
darwin/amd64)
	echo "embed-msb-runtime: no upstream assets for darwin/amd64; building without the embedded pair"
	rm -f internal/msbembed/manifest_checksums.go
	exit 0
	;;
*)
	echo "embed-msb-runtime: unsupported platform ${GOOS_ARG}/${GOARCH_ARG}" >&2
	exit 1
	;;
esac

base_url="https://github.com/superradcompany/microsandbox/releases/download/${sdk_version}"
asset_dir="internal/msbembed/assets"
manifest="internal/msbembed/manifest_checksums.go"

hash_file() {
	if command -v sha256sum >/dev/null 2>&1; then
		sha256sum "$1" | awk '{print $1}'
	else
		shasum -a 256 "$1" | awk '{print $1}'
	fi
}

mkdir -p "${asset_dir}"
checksums="$(mktemp)"
trap 'rm -f "${checksums}"' EXIT
curl -fsSL -o "${checksums}" "${base_url}/checksums.sha256"

for asset in "${msb_asset}" "${lib_asset}"; do
	want="$(awk -v a="${asset}" '$NF == a {print $1}' "${checksums}")"
	if [ -z "${want}" ]; then
		echo "embed-msb-runtime: ${asset} missing from upstream checksums" >&2
		exit 1
	fi
	echo "embed-msb-runtime: fetching ${asset} (${sdk_version})"
	curl -fsSL --retry 3 -o "${asset_dir}/${asset}" "${base_url}/${asset}"
	got="$(hash_file "${asset_dir}/${asset}")"
	if [ "${got}" != "${want}" ]; then
		echo "embed-msb-runtime: checksum mismatch for ${asset}: got ${got}, want ${want}" >&2
		rm -f "${asset_dir}/${asset}"
		exit 1
	fi
done

{
	echo "// Code generated by scripts/embed-msb-runtime.sh; DO NOT EDIT."
	echo "// Checksums verified against upstream checksums.sha256 (${sdk_version})."
	echo "package msbembed"
	echo
	echo "func init() {"
	printf '\tassetChecksums["%s"] = "%s"\n' "${msb_asset}" "$(hash_file "${asset_dir}/${msb_asset}")"
	printf '\tassetChecksums["%s"] = "%s"\n' "${lib_asset}" "$(hash_file "${asset_dir}/${lib_asset}")"
	echo "}"
} >"${manifest}"

echo "embed-msb-runtime: pair embedded for ${GOOS_ARG}/${GOARCH_ARG} at SDK ${sdk_version}"
