package config

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/pelletier/go-toml/v2"
)

// PackagesConfig represents the user-defined packages configuration.
type PackagesConfig struct {
	Apt   AptConfig   `toml:"apt"`
	Brew  BrewConfig  `toml:"brew"`
	Npm   NpmConfig   `toml:"npm"`
	Pip   PipConfig   `toml:"pip"`
	Tools ToolsConfig `toml:"tools"`
}

// AptConfig holds APT package settings.
type AptConfig struct {
	Packages []string `toml:"packages"`
}

// BrewConfig holds Homebrew package and tap settings.
type BrewConfig struct {
	Taps     []string `toml:"taps"`
	Packages []string `toml:"packages"`
}

// NpmConfig holds NPM package settings.
type NpmConfig struct {
	Packages []string `toml:"packages"`
}

// PipConfig holds PIP package settings.
type PipConfig struct {
	Packages []string `toml:"packages"`
}

// ToolsConfig holds specialized tool toggles.
type ToolsConfig struct {
	PhpBrew bool `toml:"phpbrew"`
	Nix     bool `toml:"nix"`
	Vmr     bool `toml:"vmr"`
	Asdf    bool `toml:"asdf"`
	Mise    bool `toml:"mise"`
}

// LoadPackages reads the packages.toml file.
func LoadPackages() (*PackagesConfig, error) {
	configPath := filepath.Join(GetConfigDir(), "packages.toml")

	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		return &PackagesConfig{}, nil
	}

	data, err := os.ReadFile(configPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read packages.toml: %w", err)
	}

	var config PackagesConfig
	if err := toml.Unmarshal(data, &config); err != nil {
		return nil, fmt.Errorf("failed to parse packages.toml: %w", err)
	}

	return &config, nil
}

// SavePackages writes the packages config back to packages.toml.
func (c *PackagesConfig) SavePackages() error {
	configPath := filepath.Join(GetConfigDir(), "packages.toml")

	data, err := toml.Marshal(c)
	if err != nil {
		return fmt.Errorf("failed to marshal packages config: %w", err)
	}

	if err := os.WriteFile(configPath, data, 0644); err != nil {
		return fmt.Errorf("failed to write packages.toml: %w", err)
	}

	return nil
}

// GenerateInstallScript generates a bash script to install configured packages.
func (c *PackagesConfig) GenerateInstallScript() string {
	script := "#!/bin/bash\n# Generated by Construct CLI - DO NOT EDIT\n\nset -e\n\n"

	// Initialize Homebrew environment
	script += "# Initialize Homebrew environment\n"
	script += "if [ -f /home/linuxbrew/.linuxbrew/bin/brew ]; then\n"
	script += "    eval \"$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)\"\n"
	script += "fi\n\n"

	// Standard Tools (Always installed)
	script += "echo 'Installing Claude Code...'\n"
	script += "curl -fsSL https://claude.ai/install.sh | bash\n\n"

	script += "echo 'Installing mcp-cli-ent...'\n"
	script += "curl -fsSL https://raw.githubusercontent.com/EstebanForge/mcp-cli-ent/main/scripts/install.sh | bash\n\n"

	// Specialized Tools (Priority)
	if c.Tools.PhpBrew {
		script += "echo 'Installing PHPBrew...'\n"
		script += "curl -L -O https://github.com/phpbrew/phpbrew/releases/latest/download/phpbrew.phar\n"
		script += "chmod +x phpbrew.phar\n"
		script += "sudo mv phpbrew.phar /usr/local/bin/phpbrew\n\n"
	}

	if c.Tools.Nix {
		script += "echo 'Installing Nix...'\n"
		script += "sh <(curl --proto '=https' --tlsv1.2 -L https://nixos.org/nix/install) --no-daemon\n\n"
	}

	if c.Tools.Vmr {
		script += "echo 'Installing VMR...'\n"
		script += "curl --proto '=https' --tlsv1.2 -sSf https://scripts.vmr.dpdns.org | sh\n\n"
	}

	if c.Tools.Asdf {
		script += "echo 'Installing asdf via Homebrew...'\n"
		script += "brew install asdf\n\n"
	}

	if c.Tools.Mise {
		script += "echo 'Installing mise via Homebrew...'\n"
		script += "brew install mise\n\n"
	}

	// APT
	if len(c.Apt.Packages) > 0 {
		script += "echo 'Installing APT packages...'\n"
		script += "sudo apt-get update\n"
		script += "sudo apt-get install -y "
		for _, pkg := range c.Apt.Packages {
			script += pkg + " "
		}
		script += "\n\n"
	}

	// Brew
	if len(c.Brew.Taps) > 0 || len(c.Brew.Packages) > 0 {
		script += "echo 'Installing Homebrew packages...'\n"
		for _, tap := range c.Brew.Taps {
			script += "brew tap " + tap + "\n"
		}
		if len(c.Brew.Packages) > 0 {
			script += "brew install "
			for _, pkg := range c.Brew.Packages {
				script += pkg + " "
			}
			script += "\n"
		}
		script += "\n"
	}

	// NPM
	if len(c.Npm.Packages) > 0 {
		script += "echo 'Installing NPM packages...'\n"
		script += "npm install -g "
		for _, pkg := range c.Npm.Packages {
			script += pkg + " "
		}
		script += "\n\n"
	}

	// PIP
	if len(c.Pip.Packages) > 0 {
		script += "echo 'Installing PIP packages...'\n"
		script += "pip install "
		for _, pkg := range c.Pip.Packages {
			script += pkg + " "
		}
		script += "\n\n"
	}

	script += "echo 'User package installation completed successfully.'\n"
	return script
}
